# Author: PB and Codex
# Date: 2026-05-18
# License: (c) HRDAG, 2026, GPL-2 or newer
#
# ---
# src/tfcs_fleet_tui/mock_data.py

"""Static fleet fixture for the initial dashboard mock."""

from __future__ import annotations

from tfcs_fleet_tui.model import FleetNode, FleetSnapshot


MOCK_SNAPSHOT = FleetSnapshot(
    source="mock fleet fixture",
    nodes=(
        FleetNode(
            host="scott",
            roles=("compute", "gpu", "backup_source"),
            last_update="8s",
            up="ok",
            load="3.1/64",
            cpu_temp="54C",
            hdd_temp="--",
            ssd_temp="41C",
            nvme_temp="67C",
            nic="ok",
            root="62%",
            data="71%",
            pulls="4",
            note="busy pulls",
        ),
        FleetNode(
            host="chll",
            roles=("offsite_backup", "storage", "ipfs"),
            last_update="11s",
            up="ok",
            load="0.8/32",
            cpu_temp="49C",
            hdd_temp="38C",
            ssd_temp="--",
            nvme_temp="45C",
            nic="ok",
            root="55%",
            data="82%",
            pulls="1",
        ),
        FleetNode(
            host="ipfs1",
            roles=("storage", "ipfs"),
            last_update="9s",
            up="ok",
            load="0.5/8",
            cpu_temp="46C",
            hdd_temp="42C",
            ssd_temp="--",
            nvme_temp="51C",
            nic="ok",
            root="39%",
            data="74%",
            pulls="--",
        ),
        FleetNode(
            host="pihost",
            roles=("environment", "ipfs"),
            last_update="14s",
            up="ok",
            load="0.2/4",
            cpu_temp="51C",
            hdd_temp="--",
            ssd_temp="--",
            nvme_temp="--",
            nic="ok",
            root="44%",
            data="44%",
            pulls="--",
        ),
        FleetNode(
            host="meerkat",
            roles=("compute", "ipfs"),
            last_update="7s",
            up="ok",
            load="1.7/20",
            cpu_temp="58C",
            hdd_temp="--",
            ssd_temp="--",
            nvme_temp="49C",
            nic="ok",
            root="61%",
            data="61%",
            pulls="--",
        ),
        FleetNode(
            host="snowball",
            roles=("tfc_partner",),
            last_update="13s",
            up="ok",
            load="7.4/32",
            cpu_temp="91C",
            hdd_temp="--",
            ssd_temp="--",
            nvme_temp="61C",
            nic="ok",
            root="40%",
            data="68%",
            pulls="2",
            note="cpu warm",
        ),
        FleetNode(
            host="lizo",
            roles=("tfc_partner", "storage"),
            last_update="10s",
            up="ok",
            load="0.9/16",
            cpu_temp="47C",
            hdd_temp="37C",
            ssd_temp="--",
            nvme_temp="43C",
            nic="ok",
            root="46%",
            data="79%",
            pulls="3",
        ),
        FleetNode(
            host="ben",
            roles=("storage",),
            last_update="15s",
            up="ok",
            load="2.2/32",
            cpu_temp="52C",
            hdd_temp="41C",
            ssd_temp="--",
            nvme_temp="56C",
            nic="ok",
            root="58%",
            data="64%",
            pulls="--",
        ),
        FleetNode(
            host="ida",
            roles=("tfc_partner", "storage"),
            last_update="5m",
            up="stale",
            load="--",
            cpu_temp="?",
            hdd_temp="?",
            ssd_temp="--",
            nvme_temp="?",
            nic="?",
            root="?",
            data="?",
            pulls="--",
            note="no scrape 5m",
        ),
        FleetNode(
            host="ant",
            roles=("tfc_partner", "storage"),
            last_update="12s",
            up="ok",
            load="1.1/16",
            cpu_temp="50C",
            hdd_temp="39C",
            ssd_temp="--",
            nvme_temp="72C",
            nic="ok",
            root="48%",
            data="77%",
            pulls="2",
            note="nvme warm",
        ),
        FleetNode(
            host="nas",
            roles=("storage", "ups_nut", "ipfs"),
            last_update="10s",
            up="ok",
            load="1.6/16",
            cpu_temp="48C",
            hdd_temp="44C",
            ssd_temp="--",
            nvme_temp="53C",
            nic="ok",
            root="52%",
            data="86%",
            pulls="--",
        ),
        FleetNode(
            host="kj",
            roles=("compute", "gpu"),
            last_update="9s",
            up="ok",
            load="4.8/64",
            cpu_temp="57C",
            hdd_temp="--",
            ssd_temp="--",
            nvme_temp="46C",
            nic="ok",
            root="45%",
            data="69%",
            pulls="--",
        ),
    ),
)
