# Author: PB and Claude
# Date: 2026-02-14
# License: (c) HRDAG, 2025, GPL-2 or newer
#
# ---
# src/tfcs_tui/mock.py

"""Mock data for --mock mode. Matches /status endpoint shape."""

from __future__ import annotations

STATUSES = [
    {
        "node_id": "scott.hrdag.net",
        "node_class": "active",
        "cluster": "hrdag-ofc",
        "seq": 1234,
        "uptime_seconds": 864000.0,
        "alive_peers": 6,
        "active_claims": 0,
        "wants_count": 423,
        "haves_count": 138,
        "store_count": 138,
        "version": "0.2.6",
        "capacity_gb": 500.0,
        "free_gb": 250.0,
        "claims": [],
    },
    {
        "node_id": "lizo.hrdag.net",
        "node_class": "active",
        "cluster": "cdmx",
        "seq": 45,
        "uptime_seconds": 72000.0,
        "alive_peers": 6,
        "active_claims": 1,
        "wants_count": 423,
        "haves_count": 12,
        "store_count": 12,
        "version": "0.2.6",
        "capacity_gb": 2000.0,
        "free_gb": 1800.0,
        "claims": [{"commit": "547652abcdef", "source": "scott.hrdag.net",
                    "size": 52_428_800, "bytes_transmitted": 31_457_280,
                    "rate_mbps": 8.5}],
    },
    {
        "node_id": "chll.hrdag.net",
        "node_class": "archive",
        "cluster": "chll",
        "seq": 98,
        "uptime_seconds": 360000.0,
        "alive_peers": 6,
        "active_claims": 1,
        "wants_count": 423,
        "haves_count": 15,
        "store_count": 15,
        "version": "0.2.6",
        "capacity_gb": 2000.0,
        "free_gb": 1200.0,
        "claims": [{"commit": "3ed225fedcba", "source": "scott.hrdag.net",
                    "size": 48_000_000, "bytes_transmitted": 48_000_000,
                    "rate_mbps": 12.1}],
    },
    {
        "node_id": "ipfs1.hrdag.net",
        "node_class": "storage",
        "cluster": "1015svn",
        "seq": 856,
        "uptime_seconds": 500000.0,
        "alive_peers": 6,
        "active_claims": 2,
        "wants_count": 423,
        "haves_count": 85,
        "store_count": 85,
        "version": "0.2.6",
        "capacity_gb": 1000.0,
        "free_gb": 500.0,
        "claims": [
            {"commit": "868562aaa111", "source": "scott.hrdag.net",
             "size": 50_000_000, "bytes_transmitted": 5_000_000,
             "rate_mbps": 4.2},
            {"commit": "a1b2c3d4e5f6", "source": "meerkat.hrdag.net",
             "size": 35_000_000, "bytes_transmitted": 20_000_000,
             "rate_mbps": 11.0},
        ],
    },
    {
        "node_id": "meerkat.hrdag.net",
        "node_class": "storage",
        "cluster": "1015svn",
        "seq": 823,
        "uptime_seconds": 400000.0,
        "alive_peers": 6,
        "active_claims": 1,
        "wants_count": 423,
        "haves_count": 82,
        "store_count": 82,
        "version": "0.2.6",
        "capacity_gb": 1000.0,
        "free_gb": 900.0,
        "claims": [{"commit": "7f62ea999888", "source": "scott.hrdag.net",
                    "size": 50_000_000, "bytes_transmitted": 25_000_000,
                    "rate_mbps": 9.8}],
    },
    {
        "node_id": "pihost.hrdag.net",
        "node_class": "storage",
        "cluster": "hrdag-ofc",
        "seq": 810,
        "uptime_seconds": 350000.0,
        "alive_peers": 6,
        "active_claims": 2,
        "wants_count": 423,
        "haves_count": 80,
        "store_count": 80,
        "version": "0.2.6",
        "capacity_gb": 500.0,
        "free_gb": 42.0,
        "claims": [
            {"commit": "cc1122334455", "source": "scott.hrdag.net",
             "size": 45_000_000, "bytes_transmitted": 10_000_000,
             "rate_mbps": 3.1},
            {"commit": "dd6677889900", "source": "meerkat.hrdag.net",
             "size": 52_000_000, "bytes_transmitted": 52_000_000,
             "rate_mbps": 0.0},
        ],
    },
    {
        "node_id": "snowball.hrdag.net",
        "node_class": "storage",
        "cluster": "hrdag-ofc",
        "seq": 790,
        "uptime_seconds": 300000.0,
        "alive_peers": 5,
        "active_claims": 1,
        "wants_count": 423,
        "haves_count": 70,
        "store_count": 70,
        "version": "0.2.5",
        "capacity_gb": 2000.0,
        "free_gb": 1500.0,
        "claims": [{"commit": "ee1122aabb33", "source": "ipfs1.hrdag.net",
                    "size": 40_000_000, "bytes_transmitted": 38_000_000,
                    "rate_mbps": 15.2}],
    },
]

NODE_STATUS = {
    "scott.hrdag.net": "alive",
    "lizo.hrdag.net": "alive",
    "chll.hrdag.net": "alive",
    "ipfs1.hrdag.net": "alive",
    "meerkat.hrdag.net": "alive",
    "pihost.hrdag.net": "alive",
    "snowball.hrdag.net": "suspect",
}

HEARTBEAT_AGE = {
    "scott.hrdag.net": 13.2,
    "lizo.hrdag.net": 20.2,
    "chll.hrdag.net": 18.1,
    "ipfs1.hrdag.net": 0.7,
    "meerkat.hrdag.net": 22.9,
    "pihost.hrdag.net": 3.8,
    "snowball.hrdag.net": 20.6,
}

REPLICATION = {
    0: 180,
    1: 120,
    2: 80,
    3: 43,
}
